import './globals.css'
import type { Metadata } from 'next'
import { NavProvider } from '#/context/nav.context'
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <NavProvider>
                <body>{children}</body>
            </NavProvider>
        </html>
    )
}
